# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'


jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm test
    displayName: 'Install Dependencies and Run Tests'

- job: DeployToKubernetes
  displayName: 'Deploy to Kubernetes'
  dependsOn: BuildAndTest
  steps:
  - task: UseHelm@0
    inputs:
      command: 'repo'
      arguments: 'add my-helm-repo $(Build.SourcesDirectory)/helm-charts'
    displayName: 'Add Helm Repository'

  - task: UseHelm@0
    inputs:
      command: 'install'
      arguments: 'my-release my-helm-repo/my-chart'
    displayName: 'Install My Chart'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'


- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
